import datetime
import ftplib
import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import pandas as pd
import requests
from dotenv import load_dotenv
from mailmerge import MailMerge
from docx2pdf import convert

load_dotenv()

# Get data from .env File
ftp_server = os.getenv('FTP_SERVER')
ftp_user = os.getenv('FTP_USER')
ftp_pass = os.getenv('FTP_PASS')

reportTemplate_path = 'C:/Users/hosttech/webDev/M122/RepTemplate/Template.docx'
reportTemplate = MailMerge(reportTemplate_path)

# Define current date and time
now = datetime.datetime.now()
current_date_time = now.strftime("%Y-%m-%d %H:%M:%S")


def create_report(coin_name, price, stop_lose, profit):
    # Replace String in Word File with correct data
    reportTemplate.merge(
        CoinName=str(coin_name),
        Price=str(price),
        StopLose=str(stop_lose),
        Profit=str(profit))
    reportTemplate.write('C:/Users/hosttech/webDev/M122/Report/Report.docx')
    convert('C:/Users/hosttech/webDev/M122/Report/Report.docx',
            'C:/Users/hosttech/webDev/M122/Report/Report.pdf')
    upload_report()
    send_report()


def upload_report():
    # Define FTP session
    session = ftplib.FTP(ftp_server, ftp_user, ftp_pass)
    # File to send
    file = open('C:/Users/hosttech/webDev/M122/Report/Report.pdf', 'rb')
    # Store the file with correct date and time
    session.storbinary('STOR M122/Report_'+current_date_time+'.pdf', file)
    # Close file and FTP
    file.close()
    session.quit()


def send_report():
    port = 2525
    smtp_server = "smtp.mailtrap.io"
    login = "9a392e1c367f35"  # paste your login generated by Mailtrap
    password = "b61af813ff8297"  # paste your password generated by Mailtrap

    # Add subject to email
    subject = "New Position on FTX"
    sender_email = "mailtrap@example.com"
    receiver_email = "new@example.com"

    message = MIMEMultipart()
    message["From"] = sender_email
    message["To"] = receiver_email
    message["Subject"] = subject

    # Add body to email
    body = "A new Position was created. See Certificate in Attachment. Created at: %s" %current_date_time
    message.attach(MIMEText(body, "plain"))

    filename = 'C:/Users/hosttech/webDev/M122/Report/Report.pdf'
    # Open PDF file in binary mode
    with open(filename, "rb") as attachment:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(attachment.read())

    # Encode to base64
    encoders.encode_base64(part)

    # Add header and named file
    part.add_header(
        "Content-Disposition",
        "attachment; filename= Report.pdf",
    )

    # Add attachment to message and convert it to string
    message.attach(part)
    text = message.as_string()

    # send email with logindata
    with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
        server.login(login, password)
        server.sendmail(
            sender_email, receiver_email, text
        )
    print('Sent')

    # Remove PDF
    os.remove('C:/Users/hosttech/webDev/M122/Report/Report.docx')
    os.remove('C:/Users/hosttech/webDev/M122/Report/Report.pdf')

