import ftplib
import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from time import sleep

import requests
from dotenv import load_dotenv
from mailmerge import MailMerge
from docx2pdf import convert

load_dotenv()

ftp_server = os.getenv('FTP_SERVER')
ftp_user = os.getenv('FTP_USER')
ftp_pass = os.getenv('FTP_PASS')

reportTemplate_path = 'C:/Users/hosttech/webDev/M122/RepTemplate/Template.docx'
reportTemplate = MailMerge(reportTemplate_path)


def create_report(coin_name, stop_lose, profit):
    coin_data = requests.get('https://ftx.com/api/markets/' + coin_name).json()
    reportTemplate.merge(
        CoinName=str(coin_data['result']['name']),
        Price=str(coin_data['result']['last']),
        StopLose=str(stop_lose),
        Profit=str(profit))
    reportTemplate.write('C:/Users/hosttech/webDev/M122/Report/Report.docx')
    convert('C:/Users/hosttech/webDev/M122/Report/Report.docx',
            'C:/Users/hosttech/webDev/M122/Report/Report.pdf')
    upload_report()
    send_report()


def upload_report():
    session = ftplib.FTP(ftp_server, ftp_user, ftp_pass)
    file = open('C:/Users/hosttech/webDev/M122/Report/Report.pdf', 'rb')  # file to send
    session.storbinary('STOR Report.pdf', file)  # send the file
    file.close()  # close file and FTP
    session.quit()


def send_report():
    port = 2525
    smtp_server = "smtp.mailtrap.io"
    login = "9a392e1c367f35"  # paste your login generated by Mailtrap
    password = "b61af813ff8297"  # paste your password generated by Mailtrap

    subject = "An example of boarding pass"
    sender_email = "mailtrap@example.com"
    receiver_email = "new@example.com"

    message = MIMEMultipart()
    message["From"] = sender_email
    message["To"] = receiver_email
    message["Subject"] = subject

    # Add body to email
    body = "A new Position was created. See Certificate in Attachment"
    message.attach(MIMEText(body, "plain"))

    filename = 'C:/Users/hosttech/webDev/M122/Report/Report.pdf'
    # Open PDF file in binary mode

    # We assume that the file is in the directory where you run your Python script from
    with open(filename, "rb") as attachment:
        # The content type "application/octet-stream" means that a MIME attachment is a binary file
        part = MIMEBase("application", "octet-stream")
        part.set_payload(attachment.read())

    # Encode to base64
    encoders.encode_base64(part)

    # Add header
    part.add_header(
        "Content-Disposition",
        "attachment; filename= Report.pdf",
    )

    # Add attachment to your message and convert it to string
    message.attach(part)
    text = message.as_string()

    # send your email
    with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
        server.login(login, password)
        server.sendmail(
            sender_email, receiver_email, text
        )
    print('Sent')
    os.remove('C:/Users/hosttech/webDev/M122/Report/Report.docx')
    os.remove('C:/Users/hosttech/webDev/M122/Report/Report.pdf')

