import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from socket import gaierror


class SendMail:
    def __init__(self):
        port = 2525
        smtp_server = "smtp.mailtrap.io"
        login = "9a392e1c367f35"  # paste your login generated by Mailtrap
        password = "b61af813ff8297"  # paste your password generated by Mailtrap

        subject = "An example of boarding pass"
        sender_email = "mailtrap@example.com"
        receiver_email = "new@example.com"

        message = MIMEMultipart()
        message["From"] = sender_email
        message["To"] = receiver_email
        message["Subject"] = subject

        # Add body to email
        body = "A new Position was created. See Top 10 in Attachment"
        message.attach(MIMEText(body, "plain"))

        filename = "test.txt"
        # Open PDF file in binary mode

        # We assume that the file is in the directory where you run your Python script from
        with open(filename, "rb") as attachment:
            # The content type "application/octet-stream" means that a MIME attachment is a binary file
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())

        # Encode to base64
        encoders.encode_base64(part)

        # Add header
        part.add_header(
            "Content-Disposition",
            f"attachment; filename= {filename}",
        )

        # Add attachment to your message and convert it to string
        message.attach(part)
        text = message.as_string()

        # send your email
        with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
            server.login(login, password)
            server.sendmail(
                sender_email, receiver_email, text
            )
        print('Sent')